[package]
name = "gf2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vl_big_ints = {path = "../sprzom-lab1_2/cp1"}

[dev-dependencies]
csv = "1.3.0"
rand = "0.8.5"

